--------------------------------------------------------
--  DDL for Table ATTACH
--------------------------------------------------------

  CREATE TABLE "NADURI"."ATTACH" 
   (	"ATTACH_NO" NUMBER, 
	"ATTACH_NAME" VARCHAR2(300 BYTE), 
	"A_STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"A_PATH" VARCHAR2(255 BYTE), 
	"A_TYPE" CHAR(1 BYTE), 
	"RNO" NUMBER, 
	"M_NO" NUMBER(6,0), 
	"SPOT_ID" NUMBER, 
	"N_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."ATTACH"."ATTACH_NO" IS '파일 번호';
   COMMENT ON COLUMN "NADURI"."ATTACH"."ATTACH_NAME" IS '파일 이름';
   COMMENT ON COLUMN "NADURI"."ATTACH"."A_STATUS" IS '파일 상태';
   COMMENT ON COLUMN "NADURI"."ATTACH"."A_PATH" IS '파일 경로';
   COMMENT ON COLUMN "NADURI"."ATTACH"."A_TYPE" IS '파일 타입';
   COMMENT ON COLUMN "NADURI"."ATTACH"."RNO" IS '리뷰 식별자';
   COMMENT ON COLUMN "NADURI"."ATTACH"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."ATTACH"."SPOT_ID" IS '장소 식별자';
   COMMENT ON COLUMN "NADURI"."ATTACH"."N_NO" IS '공지사항 번호';
--------------------------------------------------------
--  DDL for Table BOOKMARK
--------------------------------------------------------

  CREATE TABLE "NADURI"."BOOKMARK" 
   (	"MARK_ID" NUMBER, 
	"L_NO" NUMBER, 
	"M_NO" NUMBER, 
	"RNO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."BOOKMARK"."MARK_ID" IS '찜 식별자';
   COMMENT ON COLUMN "NADURI"."BOOKMARK"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."BOOKMARK"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."BOOKMARK"."RNO" IS '리뷰 식별자';
--------------------------------------------------------
--  DDL for Table HERITAGE
--------------------------------------------------------

  CREATE TABLE "NADURI"."HERITAGE" 
   (	"H_ID" NUMBER, 
	"L_NO" NUMBER, 
	"H_TITLE" VARCHAR2(100 BYTE), 
	"H_WIDTH" VARCHAR2(50 BYTE), 
	"H_EVENTS" VARCHAR2(100 BYTE), 
	"H_CATEGORY" VARCHAR2(100 BYTE), 
	"H_DATE" VARCHAR2(50 BYTE), 
	"H_LOCATION" VARCHAR2(300 BYTE), 
	"H_PERIOD" VARCHAR2(50 BYTE), 
	"H_LAT" VARCHAR2(100 BYTE), 
	"H_ADMIN" VARCHAR2(100 BYTE), 
	"H_LONG" VARCHAR2(100 BYTE), 
	"H_STATUS" CHAR(1 BYTE), 
	"H_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_ID" IS '문화재 식별자';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_TITLE" IS '문화재명';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_WIDTH" IS '면적';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_CATEGORY" IS '종목';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_DATE" IS '지정일';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_LOCATION" IS '소재지';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_PERIOD" IS '시대';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_ADMIN" IS '관리자';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_LONG" IS '경도';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_STATUS" IS '상태';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_COUNT" IS '조회수';
--------------------------------------------------------
--  DDL for Table KEYWORD
--------------------------------------------------------

  CREATE TABLE "NADURI"."KEYWORD" 
   (	"KEYWORD_ID" NUMBER, 
	"KEYWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."KEYWORD"."KEYWORD_ID" IS '키워드 식별자';
   COMMENT ON COLUMN "NADURI"."KEYWORD"."KEYWORD" IS '키워드';
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "NADURI"."LOCATION" 
   (	"L_NO" NUMBER, 
	"LS_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."LOCATION"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."LOCATION"."LS_CODE" IS '장소코드';
--------------------------------------------------------
--  DDL for Table LOCATION_KEYWORD
--------------------------------------------------------

  CREATE TABLE "NADURI"."LOCATION_KEYWORD" 
   (	"L_NO" NUMBER, 
	"KEYWORD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."LOCATION_KEYWORD"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."LOCATION_KEYWORD"."KEYWORD_ID" IS '키워드 식별자';
--------------------------------------------------------
--  DDL for Table LOCATION_SORT
--------------------------------------------------------

  CREATE TABLE "NADURI"."LOCATION_SORT" 
   (	"LS_CODE" NUMBER, 
	"LS_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."LOCATION_SORT"."LS_CODE" IS '장소코드';
   COMMENT ON COLUMN "NADURI"."LOCATION_SORT"."LS_NAME" IS '장소분류명';
--------------------------------------------------------
--  DDL for Table MCHOICE
--------------------------------------------------------

  CREATE TABLE "NADURI"."MCHOICE" 
   (	"M_NO" NUMBER(6,0), 
	"KEYWORD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."MCHOICE"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."MCHOICE"."KEYWORD_ID" IS '키워드 식별자';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "NADURI"."MEMBER" 
   (	"M_NO" NUMBER(6,0), 
	"M_ID" VARCHAR2(50 BYTE), 
	"M_AUTH" VARCHAR2(50 BYTE), 
	"M_PWD" VARCHAR2(50 BYTE), 
	"M_NAME" VARCHAR2(50 BYTE), 
	"M_BIRTH" VARCHAR2(50 BYTE), 
	"M_GENDER" CHAR(1 BYTE), 
	"M_ADDRESS" VARCHAR2(300 BYTE), 
	"M_EMAIL" VARCHAR2(50 BYTE), 
	"M_PHONE" VARCHAR2(30 BYTE), 
	"M_STATUS" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."MEMBER"."M_NO" IS '회원 번호';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_ID" IS '회원 아이디';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_AUTH" IS '회원 등급';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_PWD" IS '비밀번호';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_NAME" IS '이름';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_BIRTH" IS '생년월일';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_GENDER" IS '성별';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_ADDRESS" IS '주소';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_EMAIL" IS '이메일';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_PHONE" IS '전화번호';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_STATUS" IS '탈퇴 여부';

--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "NADURI"."NOTICE" 
   (	"N_NO" NUMBER, 
	"N_TITLE" VARCHAR2(300 BYTE), 
	"N_CONTENT" VARCHAR2(3000 BYTE), 
	"N_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."NOTICE"."N_NO" IS '공지사항번호';
   COMMENT ON COLUMN "NADURI"."NOTICE"."N_TITLE" IS '제목';
   COMMENT ON COLUMN "NADURI"."NOTICE"."N_CONTENT" IS '내용';
   COMMENT ON COLUMN "NADURI"."NOTICE"."N_DATE" IS '작성일';
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "NADURI"."QNA" 
   (	"QNO" NUMBER, 
	"M_NO" NUMBER, 
	"Q_CONTENT" VARCHAR2(1000 BYTE), 
	"Q_DATE" DATE, 
	"Q_UPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."QNA"."QNO" IS 'QNA 식별자';
   COMMENT ON COLUMN "NADURI"."QNA"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."QNA"."Q_CONTENT" IS '내용';
   COMMENT ON COLUMN "NADURI"."QNA"."Q_DATE" IS '작성일';
   COMMENT ON COLUMN "NADURI"."QNA"."Q_UPDATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "NADURI"."REPLY" 
   (	"REPLYNO" NUMBER, 
	"M_NO" NUMBER, 
	"RNO" NUMBER, 
	"QNO" NUMBER, 
	"REPLY_CONTENT" VARCHAR2(1000 BYTE), 
	"REPLY_DATE" DATE, 
	"REPLY_UPDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."REPLY"."REPLYNO" IS '댓글 식별자';
   COMMENT ON COLUMN "NADURI"."REPLY"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."REPLY"."RNO" IS '리뷰 식별자';
   COMMENT ON COLUMN "NADURI"."REPLY"."QNO" IS 'QNA 식별자';
   COMMENT ON COLUMN "NADURI"."REPLY"."REPLY_CONTENT" IS '내용';
   COMMENT ON COLUMN "NADURI"."REPLY"."REPLY_DATE" IS '작성일';
   COMMENT ON COLUMN "NADURI"."REPLY"."REPLY_UPDATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "NADURI"."REVIEW" 
   (	"RNO" NUMBER, 
	"L_NO" NUMBER, 
	"M_NO" NUMBER, 
	"R_RANK" NUMBER, 
	"R_TITLE" VARCHAR2(300 BYTE), 
	"R_CONTENT" VARCHAR2(3000 BYTE), 
	"R_PERIOD" VARCHAR2(50 BYTE), 
	"R_WITH" NUMBER, 
	"R_DATE" DATE, 
	"R_UPDATE" DATE, 
	"R_COUNT" NUMBER, 
	"R_STATUS" CHAR(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."REVIEW"."RNO" IS '리뷰 식별자';
   COMMENT ON COLUMN "NADURI"."REVIEW"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_RANK" IS '평점';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_TITLE" IS '제목';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_CONTENT" IS '내용';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_PERIOD" IS '방문기간';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_WITH" IS '누구와방문';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_DATE" IS '작성일';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_UPDATE" IS '수정일';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_COUNT" IS '조회수';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_STATUS" IS '상태';
--------------------------------------------------------
--  DDL for Table SPOT
--------------------------------------------------------

  CREATE TABLE "NADURI"."SPOT" 
   (	"SPOT_ID" NUMBER, 
	"L_NO" NUMBER, 
	"SPOT_NAME" VARCHAR2(100 BYTE), 
	"SPOT_TYPE" VARCHAR2(50 BYTE), 
	"SPOT_TEL" VARCHAR2(30 BYTE), 
	"SPOT_TIME" VARCHAR2(50 BYTE), 
	"SPOT_LOCATION" VARCHAR2(300 BYTE), 
	"SPOT_LAT" NUMBER, 
	"SPOT_LONG" NUMBER, 
	"S_STATUS" CHAR(1 BYTE), 
	"SPOT_DATE" DATE, 
	"SPOT_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_ID" IS '장소 식별자';
   COMMENT ON COLUMN "NADURI"."SPOT"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_NAME" IS '장소명';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_TYPE" IS '분류';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_TEL" IS '전화번호';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_TIME" IS '운영시간';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_LOCATION" IS '위치';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_LAT" IS '위도';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_LONG" IS '경도';
   COMMENT ON COLUMN "NADURI"."SPOT"."S_STATUS" IS '상태';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_DATE" IS '작성일';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_COUNT" IS '조회수';
REM INSERTING into NADURI.ATTACH
SET DEFINE OFF;
REM INSERTING into NADURI.BOOKMARK
SET DEFINE OFF;
REM INSERTING into NADURI.HERITAGE
SET DEFINE OFF;
REM INSERTING into NADURI.KEYWORD
SET DEFINE OFF;
REM INSERTING into NADURI.LOCATION
SET DEFINE OFF;
REM INSERTING into NADURI.LOCATION_KEYWORD
SET DEFINE OFF;
REM INSERTING into NADURI.LOCATION_SORT
SET DEFINE OFF;
REM INSERTING into NADURI.MCHOICE
SET DEFINE OFF;
REM INSERTING into NADURI.MEMBER
SET DEFINE OFF;
REM INSERTING into NADURI.NOTICE
SET DEFINE OFF;
REM INSERTING into NADURI.QNA
SET DEFINE OFF;
REM INSERTING into NADURI.REPLY
SET DEFINE OFF;
REM INSERTING into NADURI.REVIEW
SET DEFINE OFF;
REM INSERTING into NADURI.SPOT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ATTACH
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_ATTACH" ON "NADURI"."ATTACH" ("ATTACH_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_COMMENT" ON "NADURI"."BOOKMARK" ("MARK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_HERITAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_HERITAGE" ON "NADURI"."HERITAGE" ("H_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_KEYWORD
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_KEYWORD" ON "NADURI"."KEYWORD" ("KEYWORD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOCATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_LOCATION" ON "NADURI"."LOCATION" ("L_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOCATION_SORT
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_LOCATION_SORT" ON "NADURI"."LOCATION_SORT" ("LS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_MEMBER" ON "NADURI"."MEMBER" ("M_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007456
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."SYS_C007456" ON "NADURI"."MEMBER" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007457
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."SYS_C007457" ON "NADURI"."MEMBER" ("M_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_NOTICE" ON "NADURI"."NOTICE" ("N_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_QNA
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_QNA" ON "NADURI"."QNA" ("QNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_REPLY" ON "NADURI"."REPLY" ("REPLYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_REVIEW" ON "NADURI"."REVIEW" ("RNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SPOT
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_SPOT" ON "NADURI"."SPOT" ("SPOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "PK_ATTACH" PRIMARY KEY ("ATTACH_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."ATTACH" ADD CHECK (A_STATUS IN ('Y', 'N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKMARK
--------------------------------------------------------

  ALTER TABLE "NADURI"."BOOKMARK" MODIFY ("L_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."BOOKMARK" MODIFY ("M_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."BOOKMARK" MODIFY ("RNO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."BOOKMARK" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY ("MARK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HERITAGE
--------------------------------------------------------

  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("L_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_EVENTS" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_DATE" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_LAT" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_LONG" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_STATUS" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" ADD CONSTRAINT "PK_HERITAGE" PRIMARY KEY ("H_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KEYWORD
--------------------------------------------------------

  ALTER TABLE "NADURI"."KEYWORD" ADD CONSTRAINT "PK_KEYWORD" PRIMARY KEY ("KEYWORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION" ADD CONSTRAINT "PK_LOCATION" PRIMARY KEY ("L_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."LOCATION" MODIFY ("LS_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION_KEYWORD
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION_KEYWORD" MODIFY ("KEYWORD_ID" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."LOCATION_KEYWORD" MODIFY ("L_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION_SORT
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION_SORT" ADD CONSTRAINT "PK_LOCATION_SORT" PRIMARY KEY ("LS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MCHOICE
--------------------------------------------------------

  ALTER TABLE "NADURI"."MCHOICE" MODIFY ("KEYWORD_ID" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MCHOICE" MODIFY ("M_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "NADURI"."MEMBER" ADD CHECK (M_GENDER IN('M', 'F')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CHECK (M_STATUS IN('Y', 'N')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD UNIQUE ("M_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD UNIQUE ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("M_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CHECK (M_STATUS IN('Y', 'N')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CHECK (M_GENDER IN('M', 'F')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_STATUS" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_GENDER" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_NAME" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_PWD" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_AUTH" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "NADURI"."NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("N_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."NOTICE" MODIFY ("N_DATE" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."NOTICE" MODIFY ("N_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "NADURI"."QNA" MODIFY ("M_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY ("QNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "NADURI"."REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("REPLYNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."REPLY" MODIFY ("M_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "NADURI"."REVIEW" MODIFY ("L_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" MODIFY ("M_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPOT
--------------------------------------------------------

  ALTER TABLE "NADURI"."SPOT" MODIFY ("L_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."SPOT" MODIFY ("SPOT_NAME" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."SPOT" MODIFY ("SPOT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."SPOT" ADD CONSTRAINT "PK_SPOT" PRIMARY KEY ("SPOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "FK_ATTACH_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ENABLE;
  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "FK_ATTACH_NOTICE" FOREIGN KEY ("N_NO")
	  REFERENCES "NADURI"."NOTICE" ("N_NO") ENABLE;
  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "FK_ATTACH_REVIEW" FOREIGN KEY ("RNO")
	  REFERENCES "NADURI"."REVIEW" ("RNO") ENABLE;
  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "FK_ATTACH_SPOT" FOREIGN KEY ("SPOT_ID")
	  REFERENCES "NADURI"."SPOT" ("SPOT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKMARK
--------------------------------------------------------

  ALTER TABLE "NADURI"."BOOKMARK" ADD CONSTRAINT "FK_BOOKMARK_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
  ALTER TABLE "NADURI"."BOOKMARK" ADD CONSTRAINT "FK_BOOKMARK_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ENABLE;
  ALTER TABLE "NADURI"."BOOKMARK" ADD CONSTRAINT "FK_BOOKMARK_REVIEW" FOREIGN KEY ("RNO")
	  REFERENCES "NADURI"."REVIEW" ("RNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HERITAGE
--------------------------------------------------------

  ALTER TABLE "NADURI"."HERITAGE" ADD CONSTRAINT "FK_HERITAGE_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION" ADD CONSTRAINT "FK_LOCATION_SORT" FOREIGN KEY ("LS_CODE")
	  REFERENCES "NADURI"."LOCATION_SORT" ("LS_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION_KEYWORD
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION_KEYWORD" ADD CONSTRAINT "FK_LOCATION_KEYWORD_KEYWORD" FOREIGN KEY ("KEYWORD_ID")
	  REFERENCES "NADURI"."KEYWORD" ("KEYWORD_ID") ENABLE;
  ALTER TABLE "NADURI"."LOCATION_KEYWORD" ADD CONSTRAINT "FK_LOCATION_KEYWORD_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MCHOICE
--------------------------------------------------------

  ALTER TABLE "NADURI"."MCHOICE" ADD CONSTRAINT "FK_KEYWORD_ID" FOREIGN KEY ("KEYWORD_ID")
	  REFERENCES "NADURI"."KEYWORD" ("KEYWORD_ID") ENABLE;
  ALTER TABLE "NADURI"."MCHOICE" ADD CONSTRAINT "FK_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "NADURI"."REPLY" ADD CONSTRAINT "FK_REPLY_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ENABLE;
  ALTER TABLE "NADURI"."REPLY" ADD CONSTRAINT "FK_REPLY_QNA" FOREIGN KEY ("QNO")
	  REFERENCES "NADURI"."QNA" ("QNO") ENABLE;
  ALTER TABLE "NADURI"."REPLY" ADD CONSTRAINT "FK_REPLY_REVIEW" FOREIGN KEY ("RNO")
	  REFERENCES "NADURI"."REVIEW" ("RNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "NADURI"."REVIEW" ADD CONSTRAINT "FK_REVIEW_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
  ALTER TABLE "NADURI"."REVIEW" ADD CONSTRAINT "FK_REVIEW_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPOT
--------------------------------------------------------

  ALTER TABLE "NADURI"."SPOT" ADD CONSTRAINT "FK_SPOT_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
