--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-27-2021   
--------------------------------------------------------
DROP TABLE "NADURI"."ATTACH";
DROP TABLE "NADURI"."BOOKMARK";
DROP TABLE "NADURI"."HERITAGE";
DROP TABLE "NADURI"."KEYWORD";
DROP TABLE "NADURI"."LOCATION";
DROP TABLE "NADURI"."LOCATION_KEYWORD";
DROP TABLE "NADURI"."LOCATION_SORT";
DROP TABLE "NADURI"."MCHOICE";
DROP TABLE "NADURI"."MEMBER";
DROP TABLE "NADURI"."NOTICE";
DROP TABLE "NADURI"."QNA";
DROP TABLE "NADURI"."REPLY";
DROP TABLE "NADURI"."REVIEW";
DROP TABLE "NADURI"."SPOT";
--------------------------------------------------------
--  DDL for Table ATTACH
--------------------------------------------------------

  CREATE TABLE "NADURI"."ATTACH" 
   (	"A_NO" NUMBER, 
	"A_NAME" VARCHAR2(300 BYTE), 
	"A_STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"A_PATH" VARCHAR2(255 BYTE), 
	"A_TYPE" CHAR(1 BYTE), 
	"R_NO" NUMBER, 
	"M_NO" NUMBER(6,0), 
	"SPOT_ID" NUMBER, 
	"N_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."ATTACH"."A_NO" IS '파일 번호';
   COMMENT ON COLUMN "NADURI"."ATTACH"."A_NAME" IS '파일 이름';
   COMMENT ON COLUMN "NADURI"."ATTACH"."A_STATUS" IS '파일 상태';
   COMMENT ON COLUMN "NADURI"."ATTACH"."A_PATH" IS '파일 경로';
   COMMENT ON COLUMN "NADURI"."ATTACH"."A_TYPE" IS '파일 타입';
   COMMENT ON COLUMN "NADURI"."ATTACH"."R_NO" IS '리뷰 식별자';
   COMMENT ON COLUMN "NADURI"."ATTACH"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."ATTACH"."SPOT_ID" IS '장소 식별자';
   COMMENT ON COLUMN "NADURI"."ATTACH"."N_NO" IS '공지사항 번호';
--------------------------------------------------------
--  DDL for Table BOOKMARK
--------------------------------------------------------

  CREATE TABLE "NADURI"."BOOKMARK" 
   (	"MARK_ID" NUMBER, 
	"L_NO" NUMBER, 
	"M_NO" NUMBER, 
	"R_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."BOOKMARK"."MARK_ID" IS '찜 식별자';
   COMMENT ON COLUMN "NADURI"."BOOKMARK"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."BOOKMARK"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."BOOKMARK"."R_NO" IS '리뷰 식별자';
--------------------------------------------------------
--  DDL for Table HERITAGE
--------------------------------------------------------

  CREATE TABLE "NADURI"."HERITAGE" 
   (	"H_ID" NUMBER, 
	"L_NO" NUMBER, 
	"H_TITLE" VARCHAR2(100 BYTE), 
	"H_WIDTH" VARCHAR2(50 BYTE), 
	"H_EVENTS" VARCHAR2(100 BYTE), 
	"H_CATEGORY" VARCHAR2(100 BYTE), 
	"H_DATE" VARCHAR2(50 BYTE), 
	"H_LOCATION" VARCHAR2(300 BYTE), 
	"H_PERIOD" VARCHAR2(50 BYTE), 
	"H_LAT" VARCHAR2(100 BYTE), 
	"H_ADMIN" VARCHAR2(100 BYTE), 
	"H_LONG" VARCHAR2(100 BYTE), 
	"H_STATUS" CHAR(1 BYTE), 
	"H_COUNT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_ID" IS '문화재 식별자';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_TITLE" IS '문화재명';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_WIDTH" IS '면적';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_EVENTS" IS '종목';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_CATEGORY" IS '분류';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_DATE" IS '지정일';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_LOCATION" IS '소재지';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_PERIOD" IS '시대';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_LAT" IS '위도';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_ADMIN" IS '관리자';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_LONG" IS '경도';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_STATUS" IS '상태';
   COMMENT ON COLUMN "NADURI"."HERITAGE"."H_COUNT" IS '조회수';
--------------------------------------------------------
--  DDL for Table KEYWORD
--------------------------------------------------------

  CREATE TABLE "NADURI"."KEYWORD" 
   (	"KEYWORD_ID" NUMBER, 
	"KEYWORD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."KEYWORD"."KEYWORD_ID" IS '키워드 식별자';
   COMMENT ON COLUMN "NADURI"."KEYWORD"."KEYWORD" IS '키워드';
--------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------

  CREATE TABLE "NADURI"."LOCATION" 
   (	"L_NO" NUMBER, 
	"LS_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."LOCATION"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."LOCATION"."LS_CODE" IS '장소코드';
--------------------------------------------------------
--  DDL for Table LOCATION_KEYWORD
--------------------------------------------------------

  CREATE TABLE "NADURI"."LOCATION_KEYWORD" 
   (	"L_NO" NUMBER, 
	"KEYWORD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."LOCATION_KEYWORD"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."LOCATION_KEYWORD"."KEYWORD_ID" IS '키워드 식별자';
--------------------------------------------------------
--  DDL for Table LOCATION_SORT
--------------------------------------------------------

  CREATE TABLE "NADURI"."LOCATION_SORT" 
   (	"LS_CODE" NUMBER, 
	"LS_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."LOCATION_SORT"."LS_CODE" IS '장소코드';
   COMMENT ON COLUMN "NADURI"."LOCATION_SORT"."LS_NAME" IS '장소분류명';
--------------------------------------------------------
--  DDL for Table MCHOICE
--------------------------------------------------------

  CREATE TABLE "NADURI"."MCHOICE" 
   (	"M_NO" NUMBER(6,0), 
	"KEYWORD_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."MCHOICE"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."MCHOICE"."KEYWORD_ID" IS '키워드 식별자';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "NADURI"."MEMBER" 
   (	"M_NO" NUMBER(6,0), 
	"M_ID" VARCHAR2(50 BYTE), 
	"M_AUTH" CHAR(1 BYTE) DEFAULT 1, 
	"M_PWD" VARCHAR2(50 BYTE), 
	"M_NAME" VARCHAR2(50 BYTE), 
	"M_GENDER" CHAR(1 BYTE), 
	"M_ADDRESS" VARCHAR2(300 BYTE), 
	"M_EMAIL" VARCHAR2(50 BYTE), 
	"M_PHONE" VARCHAR2(30 BYTE), 
	"M_STATUS" CHAR(1 BYTE) DEFAULT 'Y', 
	"M_BIRTH" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."MEMBER"."M_NO" IS '회원 번호';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_ID" IS '회원 아이디';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_AUTH" IS '회원 등급';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_PWD" IS '비밀번호';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_NAME" IS '이름';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_GENDER" IS '성별';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_ADDRESS" IS '주소';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_EMAIL" IS '이메일';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_PHONE" IS '전화번호';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_STATUS" IS '탈퇴 여부';
   COMMENT ON COLUMN "NADURI"."MEMBER"."M_BIRTH" IS '생년월일';
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "NADURI"."NOTICE" 
   (	"N_NO" NUMBER, 
	"N_TITLE" VARCHAR2(300 BYTE), 
	"N_CONTENT" VARCHAR2(3000 BYTE), 
	"N_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."NOTICE"."N_NO" IS '공지사항번호';
   COMMENT ON COLUMN "NADURI"."NOTICE"."N_TITLE" IS '제목';
   COMMENT ON COLUMN "NADURI"."NOTICE"."N_CONTENT" IS '내용';
   COMMENT ON COLUMN "NADURI"."NOTICE"."N_DATE" IS '작성일';
--------------------------------------------------------
--  DDL for Table QNA
--------------------------------------------------------

  CREATE TABLE "NADURI"."QNA" 
   (	"Q_NO" NUMBER, 
	"M_NO" NUMBER, 
	"Q_CONTENT" VARCHAR2(1000 BYTE), 
	"Q_DATE" DATE DEFAULT SYSDATE, 
	"Q_UPDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."QNA"."Q_NO" IS 'QNA 식별자';
   COMMENT ON COLUMN "NADURI"."QNA"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."QNA"."Q_CONTENT" IS '내용';
   COMMENT ON COLUMN "NADURI"."QNA"."Q_DATE" IS '작성일';
   COMMENT ON COLUMN "NADURI"."QNA"."Q_UPDATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "NADURI"."REPLY" 
   (	"REPLYNO" NUMBER, 
	"M_NO" NUMBER, 
	"R_NO" NUMBER, 
	"Q_NO" NUMBER, 
	"REPLY_CONTENT" VARCHAR2(1000 BYTE), 
	"REPLY_DATE" DATE DEFAULT SYSDATE, 
	"REPLY_UPDATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."REPLY"."REPLYNO" IS '댓글 식별자';
   COMMENT ON COLUMN "NADURI"."REPLY"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."REPLY"."R_NO" IS '리뷰 식별자';
   COMMENT ON COLUMN "NADURI"."REPLY"."Q_NO" IS 'QNA 식별자';
   COMMENT ON COLUMN "NADURI"."REPLY"."REPLY_CONTENT" IS '내용';
   COMMENT ON COLUMN "NADURI"."REPLY"."REPLY_DATE" IS '작성일';
   COMMENT ON COLUMN "NADURI"."REPLY"."REPLY_UPDATE" IS '수정일';
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "NADURI"."REVIEW" 
   (	"R_NO" NUMBER, 
	"L_NO" NUMBER, 
	"M_NO" NUMBER, 
	"R_RANK" NUMBER DEFAULT 3, 
	"R_TITLE" VARCHAR2(300 BYTE), 
	"R_CONTENT" VARCHAR2(3000 BYTE), 
	"R_PERIOD" VARCHAR2(50 BYTE), 
	"R_WITH" NUMBER, 
	"R_DATE" DATE DEFAULT SYSDATE, 
	"R_UPDATE" DATE DEFAULT SYSDATE, 
	"R_LIKE" NUMBER DEFAULT 0, 
	"R_COUNT" NUMBER DEFAULT 0, 
	"R_STATUS" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."REVIEW"."R_NO" IS '리뷰 식별자';
   COMMENT ON COLUMN "NADURI"."REVIEW"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."REVIEW"."M_NO" IS '회원번호';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_RANK" IS '평점';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_TITLE" IS '제목';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_CONTENT" IS '내용';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_PERIOD" IS '방문기간';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_WITH" IS '누구와방문';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_DATE" IS '작성일';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_UPDATE" IS '수정일';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_LIKE" IS '좋아요';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_COUNT" IS '조회수';
   COMMENT ON COLUMN "NADURI"."REVIEW"."R_STATUS" IS '상태';
--------------------------------------------------------
--  DDL for Table SPOT
--------------------------------------------------------

  CREATE TABLE "NADURI"."SPOT" 
   (	"SPOT_ID" NUMBER, 
	"L_NO" NUMBER, 
	"SPOT_NAME" VARCHAR2(100 BYTE), 
	"SPOT_TYPE" VARCHAR2(50 BYTE), 
	"SPOT_TEL" VARCHAR2(30 BYTE), 
	"SPOT_TIME" VARCHAR2(50 BYTE), 
	"SPOT_LOCATION" VARCHAR2(300 BYTE), 
	"SPOT_LAT" NUMBER, 
	"SPOT_LONG" NUMBER, 
	"S_STATUS" CHAR(1 BYTE), 
	"SPOT_DATE" DATE DEFAULT SYSDATE, 
	"SPOT_COUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_ID" IS '장소 식별자';
   COMMENT ON COLUMN "NADURI"."SPOT"."L_NO" IS '장소번호';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_NAME" IS '장소명';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_TYPE" IS '분류';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_TEL" IS '전화번호';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_TIME" IS '운영시간';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_LOCATION" IS '위치';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_LAT" IS '위도';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_LONG" IS '경도';
   COMMENT ON COLUMN "NADURI"."SPOT"."S_STATUS" IS '상태';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_DATE" IS '작성일';
   COMMENT ON COLUMN "NADURI"."SPOT"."SPOT_COUNT" IS '조회수';
REM INSERTING into NADURI.ATTACH
SET DEFINE OFF;
REM INSERTING into NADURI.BOOKMARK
SET DEFINE OFF;
REM INSERTING into NADURI.HERITAGE
SET DEFINE OFF;
REM INSERTING into NADURI.KEYWORD
SET DEFINE OFF;
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (43,'캠핑');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (44,'바다');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (45,'자연');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (46,'패키지');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (1,'문화재');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (2,'맛집');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (3,'쇼핑');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (4,'축제');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (5,'트래킹');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (6,'드라이브');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (7,'자전거');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (8,'사진');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (9,'반려동물');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (10,'혼자');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (11,'친구');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (12,'커플');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (13,'가족');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (14,'단체');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (15,'봄');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (16,'여름');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (17,'가을');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (18,'겨울');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (19,'궁궐');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (20,'유적지');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (21,'교육기관');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (22,'인물');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (23,'한옥');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (24,'전통');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (25,'교과서');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (26,'무덤');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (27,'건축');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (28,'종교');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (29,'술');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (30,'먹방');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (31,'카페');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (32,'데이트');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (33,'장터');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (34,'미슐랭');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (35,'골목식당');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (36,'먹킷리스트');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (37,'노포');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (38,'나만알고픈');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (39,'당일치기');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (40,'즉흥');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (41,'레트로');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (42,'힐링');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (47,'기차');
Insert into NADURI.KEYWORD (KEYWORD_ID,KEYWORD) values (48,'도심');
REM INSERTING into NADURI.LOCATION
SET DEFINE OFF;
REM INSERTING into NADURI.LOCATION_KEYWORD
SET DEFINE OFF;
REM INSERTING into NADURI.LOCATION_SORT
SET DEFINE OFF;
REM INSERTING into NADURI.MCHOICE
SET DEFINE OFF;
REM INSERTING into NADURI.MEMBER
SET DEFINE OFF;
REM INSERTING into NADURI.NOTICE
SET DEFINE OFF;
REM INSERTING into NADURI.QNA
SET DEFINE OFF;
REM INSERTING into NADURI.REPLY
SET DEFINE OFF;
REM INSERTING into NADURI.REVIEW
SET DEFINE OFF;
REM INSERTING into NADURI.SPOT
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_ATTACH
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_ATTACH" ON "NADURI"."ATTACH" ("A_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_COMMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_COMMENT" ON "NADURI"."BOOKMARK" ("MARK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_HERITAGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_HERITAGE" ON "NADURI"."HERITAGE" ("H_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_KEYWORD
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_KEYWORD" ON "NADURI"."KEYWORD" ("KEYWORD_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOCATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_LOCATION" ON "NADURI"."LOCATION" ("L_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOCATION_SORT
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_LOCATION_SORT" ON "NADURI"."LOCATION_SORT" ("LS_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_MEMBER" ON "NADURI"."MEMBER" ("M_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007456
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."SYS_C007456" ON "NADURI"."MEMBER" ("M_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007457
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."SYS_C007457" ON "NADURI"."MEMBER" ("M_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_NOTICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_NOTICE" ON "NADURI"."NOTICE" ("N_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_QNA
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_QNA" ON "NADURI"."QNA" ("Q_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REPLY
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_REPLY" ON "NADURI"."REPLY" ("REPLYNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_REVIEW" ON "NADURI"."REVIEW" ("R_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SPOT
--------------------------------------------------------

  CREATE UNIQUE INDEX "NADURI"."PK_SPOT" ON "NADURI"."SPOT" ("SPOT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "PK_ATTACH" PRIMARY KEY ("A_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."ATTACH" ADD CHECK (A_STATUS IN ('Y', 'N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOKMARK
--------------------------------------------------------

  ALTER TABLE "NADURI"."BOOKMARK" MODIFY ("L_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."BOOKMARK" MODIFY ("M_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."BOOKMARK" MODIFY ("R_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."BOOKMARK" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY ("MARK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HERITAGE
--------------------------------------------------------

  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("L_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_EVENTS" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_DATE" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_LAT" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_LONG" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" MODIFY ("H_STATUS" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."HERITAGE" ADD CONSTRAINT "PK_HERITAGE" PRIMARY KEY ("H_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KEYWORD
--------------------------------------------------------

  ALTER TABLE "NADURI"."KEYWORD" ADD CONSTRAINT "PK_KEYWORD" PRIMARY KEY ("KEYWORD_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION" ADD CONSTRAINT "PK_LOCATION" PRIMARY KEY ("L_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."LOCATION" MODIFY ("LS_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION_KEYWORD
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION_KEYWORD" MODIFY ("KEYWORD_ID" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."LOCATION_KEYWORD" MODIFY ("L_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATION_SORT
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION_SORT" ADD CONSTRAINT "PK_LOCATION_SORT" PRIMARY KEY ("LS_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MCHOICE
--------------------------------------------------------

  ALTER TABLE "NADURI"."MCHOICE" MODIFY ("KEYWORD_ID" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MCHOICE" MODIFY ("M_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "NADURI"."MEMBER" ADD CONSTRAINT "MEMBER_CHK1" CHECK (M_AUTH IN('0', '1')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CHECK (M_GENDER IN('M', 'F')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CHECK (M_STATUS IN('Y', 'N')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD UNIQUE ("M_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD UNIQUE ("M_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("M_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CHECK (M_STATUS IN('Y', 'N')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" ADD CHECK (M_GENDER IN('M', 'F')) ENABLE;
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_STATUS" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_GENDER" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_BIRTH" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_NAME" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_PWD" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_AUTH" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."MEMBER" MODIFY ("M_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "NADURI"."NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("N_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."NOTICE" MODIFY ("N_DATE" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."NOTICE" MODIFY ("N_TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table QNA
--------------------------------------------------------

  ALTER TABLE "NADURI"."QNA" MODIFY ("M_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY ("Q_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "NADURI"."REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY ("REPLYNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NADURI"."REPLY" MODIFY ("M_NO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "NADURI"."REVIEW" MODIFY ("R_WITH" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" MODIFY ("R_PERIOD" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" MODIFY ("R_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" MODIFY ("R_TITLE" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" MODIFY ("R_RANK" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" ADD CONSTRAINT "REVIEW_CHK1" CHECK (R_STATUS IN('Y', 'N')) ENABLE;
  ALTER TABLE "NADURI"."REVIEW" MODIFY ("L_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" MODIFY ("M_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("R_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SPOT
--------------------------------------------------------

  ALTER TABLE "NADURI"."SPOT" MODIFY ("L_NO" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."SPOT" MODIFY ("SPOT_NAME" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."SPOT" MODIFY ("SPOT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "NADURI"."SPOT" ADD CONSTRAINT "PK_SPOT" PRIMARY KEY ("SPOT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "FK_ATTACH_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "FK_ATTACH_NOTICE" FOREIGN KEY ("N_NO")
	  REFERENCES "NADURI"."NOTICE" ("N_NO") ENABLE;
  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "FK_ATTACH_REVIEW" FOREIGN KEY ("R_NO")
	  REFERENCES "NADURI"."REVIEW" ("R_NO") ENABLE;
  ALTER TABLE "NADURI"."ATTACH" ADD CONSTRAINT "FK_ATTACH_SPOT" FOREIGN KEY ("SPOT_ID")
	  REFERENCES "NADURI"."SPOT" ("SPOT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOOKMARK
--------------------------------------------------------

  ALTER TABLE "NADURI"."BOOKMARK" ADD CONSTRAINT "FK_BOOKMARK_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
  ALTER TABLE "NADURI"."BOOKMARK" ADD CONSTRAINT "FK_BOOKMARK_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NADURI"."BOOKMARK" ADD CONSTRAINT "FK_BOOKMARK_REVIEW" FOREIGN KEY ("R_NO")
	  REFERENCES "NADURI"."REVIEW" ("R_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HERITAGE
--------------------------------------------------------

  ALTER TABLE "NADURI"."HERITAGE" ADD CONSTRAINT "FK_HERITAGE_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION" ADD CONSTRAINT "FK_LOCATION_SORT" FOREIGN KEY ("LS_CODE")
	  REFERENCES "NADURI"."LOCATION_SORT" ("LS_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOCATION_KEYWORD
--------------------------------------------------------

  ALTER TABLE "NADURI"."LOCATION_KEYWORD" ADD CONSTRAINT "FK_LOCATION_KEYWORD_KEYWORD" FOREIGN KEY ("KEYWORD_ID")
	  REFERENCES "NADURI"."KEYWORD" ("KEYWORD_ID") ENABLE;
  ALTER TABLE "NADURI"."LOCATION_KEYWORD" ADD CONSTRAINT "FK_LOCATION_KEYWORD_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MCHOICE
--------------------------------------------------------

  ALTER TABLE "NADURI"."MCHOICE" ADD CONSTRAINT "FK_KEYWORD_ID" FOREIGN KEY ("KEYWORD_ID")
	  REFERENCES "NADURI"."KEYWORD" ("KEYWORD_ID") ENABLE;
  ALTER TABLE "NADURI"."MCHOICE" ADD CONSTRAINT "FK_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ON DELETE CASCADE ENABLE ;

--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "NADURI"."REPLY" ADD CONSTRAINT "FK_REPLY_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ON DELETE CASCADE ENABLE;
  ALTER TABLE "NADURI"."REPLY" ADD CONSTRAINT "FK_REPLY_QNA" FOREIGN KEY ("Q_NO")
	  REFERENCES "NADURI"."QNA" ("Q_NO") ENABLE;
  ALTER TABLE "NADURI"."REPLY" ADD CONSTRAINT "FK_REPLY_REVIEW" FOREIGN KEY ("R_NO")
	  REFERENCES "NADURI"."REVIEW" ("R_NO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "NADURI"."REVIEW" ADD CONSTRAINT "FK_REVIEW_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
  ALTER TABLE "NADURI"."REVIEW" ADD CONSTRAINT "FK_REVIEW_MEMBER" FOREIGN KEY ("M_NO")
	  REFERENCES "NADURI"."MEMBER" ("M_NO") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPOT
--------------------------------------------------------

  ALTER TABLE "NADURI"."SPOT" ADD CONSTRAINT "FK_SPOT_LOCATION" FOREIGN KEY ("L_NO")
	  REFERENCES "NADURI"."LOCATION" ("L_NO") ENABLE;
